### PR TITLE
Fix Coverity CID 120038 (Dereference null return value)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
I added one more patch which fixes Coverity errors.

**Comment by henning-gerhardt** [comment]
Please don't mix different fixes. Instead offer more pull requests.

**Comment by stweil** [comment]
@henning-gerhardt: Done.

**Comment by henning-gerhardt** [comment]
Mhh, introducing white space as indent in a tab indent file.

**Comment by stweil** [comment]
@henning-gerhardt, blanks are needed even in a tab indented file to align code (I aligned the arguments of assertTrue). Otherwise you can only indent with multiples of 8. That's one of the many reasons why I'd prefer banning tabs.

**Comment by henning-gerhardt** [comment]
It depends on how you configure your preferred IDE or editor. Tabs could easily displayed as 4 space indents. 

This file is with tab indent so changes should not change indent style.

**Comment by stweil** [comment]
@henning-gerhardt, yes, you can configure your editor to use tab indent with multiples of 4 spaces. That's one more reason why I don't like tabs in code: how do you tell everybody that they have to set their editors to tabwidth = 4? How is this done for the different kinds of editors for the single project (because other projects need a different setting)? Does it work with all editors? Does it also work with your printer? Does it also work with shell output? Or in the GitHub view? I'm afraid that the only answer for several of those questions is no.

If you use tabs, then the only common standard is setting tabwidth = 8, because that is the value it always had, so that's the only value which works with (nearly) any software and printer.

By the way, even with a tab width of 2 or 4, you cannot always align code with tabs only. "assertTrue(" is 11 characters, so you need 1 (tab width 2) or 3 blanks (tab width 4 or 8).

I only see two possible choices for indentation in Goobi.production:
* Use tabs with tab width 8, optionally followed by up to 7 spaces if needed for code alignment (that's what the Linux kernel uses).
* Don't use tabs. Indent with blanks, usually with multiples of 2 or 4 (that's what many other free projects use).

A blank followed by a tab is always wrong (I'm afraid that we have some of those nevertheless) and detected by Git.

**Comment by matthias-ronge** [comment]
I would prefer to follow [Google Java Style](https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters) guide here, which declares:

> […] the ASCII horizontal space character (0x20) is the only whitespace character that appears anywhere in a source file. This implies that:
> 1. All other whitespace characters in string and character literals are escaped.
> 2. Tab characters are not used for indentation.

I find this perfectly rational. Personally, I also prefer an indent of 4, not 8, and a maximum line length ≤ 110 because GitHub does not do well in horizontal scrolling.

**Comment by stweil** [comment]
@matthias-ronge I agree.

**Comment by henning-gerhardt** [comment]
I will merge this. Indent war should go to a separate issue and pull request.

**Pull request merged**
