### PR TITLE
Use SafeFile class to do null check on File list() results

### PR DESCRIPTION
**Pull request by matthias-ronge**
The branch does work now with FireBug. The SafeFile class is now included, of course. Please review carefully.

### CODE REVIEW

**Comment by stweil** [comment]
While it is good that you address this issue, I'd really appreciate if you could modify your pull request to only contain working code. It is easy on your side to combine patches and eliminate "Does not work" patches (if you need assistance, I can help). It is tedious for people reading the project history or doing `git bisect` when they have to handle such commits. It also increases the git repository unnecessarily.

**Comment by matthias-ronge** [comment]
I think this was what you meant.

**Comment by henning-gerhardt** [comment]
Two things of code style check:
- new class SafeFile needs more Java doc entries. Public methods / interfaces must have a Java doc description. 
- indent fun: changes in classes `Goobi/src/de/sub/goobi/metadaten/FileManipulation.java` and `Goobi/src/org/goobi/production/flow/helper/JobCreation.java` introducing tab indent inside space indent.

**Comment by matthias-ronge** [comment]
* SafeFile is delegate. Methods should be self explanatory or understandable from `java.io.File` or `org.apache.commons.io.FileUtils`.
 * I cannot set white space handling on a per-file basis. Goobi is tab spaced, so Eclipse uses tabs for the whole project.

**Comment by henning-gerhardt** [comment]
- `SafeFile`: can you not use `@link` or `@see` [1](http://stackoverflow.com/questions/3618185/how-can-a-methods-javadoc-be-copied-into-other-methods-javadoc) or `{@inheritDoc}` [2](http://stackoverflow.com/questions/5484375/javadoc-how-to-copy-function-description)? 
- Hell of indent: I think, this must be cleared in near future.
- Merge conflict in classes `Goobi/src/de/sub/goobi/export/download/ExportMetsWithoutHibernate.java` and `Goobi/src/de/sub/goobi/export/download/ExportMets.java`. A rebase should help.

**Comment by henning-gerhardt** [comment]
Is your master branch up to date? Today's changes are not recognized :(

**Comment by matthias-ronge** [comment]
It was not. Now it is, and rebase broke my my Eclipse’s nack, probably caused by [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=332643). It is not straightforeward. It is probably easier—and safer—to develop the code new.

**Comment by henning-gerhardt** [comment]
Sorry to read this :(

**Comment by matthias-ronge** [comment]
In branches with big changes it seems easier to merge from the master into the branch. Done.

I found some more methods in `Helper` class which are now part of SafeFile and were refactored now, too.

**Comment by matthias-ronge** [comment]
Now *all* files are showing as changed in the diff. Why? Is there a white space issue?

**Comment by henning-gerhardt** [comment]
1) Please do not merge master branch in your development branch. This is bad practise. Use git rebase instead. As Eclipse IDE has some problems with git rebase than please use an other tool like git command line tools.
2) Fetching this pull request as diff file and looking into this file I see your problem: you adding windows line endings to every file.

**Comment by stweil** [comment]
@matthias-ronge, as you develop on Windows, I suggest using Tortoise Git (or the command line) for more complex operations like squashing several commits into one, re-ordering commits or rebasing. You can still use the Eclipse git support for simple operations like viewing the history, seeing diffs or adding new commits.

**Comment by matthias-ronge** [comment]
Merging the master branch into the current branch is much easier here, otherwise I would have to redevelop all intermediate states of my branch which is just too complicate to handle.

Obviously my breakdown of eclipse and new setup of it forgot the line endings settings.

I consider this branch broken. I think the code can be rescued but it must go into a new branch or all lines of all files will remain showing as changed.

**Pull request closed without merging**
