### PR TITLE
Pull 365 addon

### PR DESCRIPTION
**Pull request by matthias-ronge**
Local ignores are possible. So remove the one remaining and add documentation.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Ignoring `.properties` and `.xml` files inside `Goobi\src` is not a good idea because you loose changes for bean hbm xml files or message translations. I did not found any `.txt` and `.xsl` files inside `Goobi\src` so ignoring could be dangerous for any future update. 

Is ignoring for this file extensions really necessary?

**Comment by matthias-ronge** [comment]
@henning-gerhardt The file exclude patterns are not applied to subdirectories. None of these files are on the repository of course.

@stweil The directory seems not to be created when checking out the github branch using the Eclipse plugin (at least on my Windows). I completely agree that it does not create empty directories and files as they only eat up disk space (though little).

**Comment by matthias-ronge** [comment]
local

**Comment by henning-gerhardt** [comment]
@matthias-ronge: I added temporally your proposed settings to my local development environment and you are right your changes are not affecting subdirectory entries.

**Comment by stweil** [comment]
I suggest combining all 4 patches in one single patch.

**Comment by matthias-ronge** [comment]
I always do many commits. Just ignore and read only the result.

**Pull request merged**
