### PR TITLE
Fix nearly all Javadoc warnings

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I tried your changes but `ant javadoc` generate some more warnings:

```
  [javadoc] Constructing Javadoc information...
  [javadoc] Standard Doclet version 1.7.0_91
  [javadoc] Building tree for all the packages and classes...
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/de/sub/goobi/forms/ProzesskopieForm.java:1919: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/de/sub/goobi/helper/encryption/MD5.java:72: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/de/sub/goobi/importer/ImportZentralblatt.java:248: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/mq/ActiveMQDirector.java:198: warning - Tag @see: can't find contextDestroyed(javax.servlet. ServletContextEvent) in javax.servlet.ServletContextListener
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/jobs/HistoryAnalyserJob.java:501: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/FilterHelper.java:885: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/FilterHelper.java:923: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/SQLGenerator.java:182: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/StatQuestProjectProgressData.java:335: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/StatQuestThroughput.java:307: warning - @return tag has no arguments.
  [javadoc] /home/gerhardt/git/goobi-production/Goobi/src/org/goobi/production/flow/statistics/hibernate/StatQuestThroughput.java:332: warning - @return tag has no arguments.
  [javadoc] Building index for all the packages and classes...
  [javadoc] Building index for all classes...
  [javadoc] Generating /home/gerhardt/git/goobi-production/build/javadoc/help-doc.html...
  [javadoc] 11 warnings
```

**Comment by stweil** [comment]
I used a newer Java version:

    [javadoc] Standard Doclet version 1.8.0_72-internal

It only reports one warning in ActiveMQDirector.java (for which I have no fix, so the subject should be "Fix nearly all warnings"). Maybe Javadoc 1.7 and 1.8 handles documentation for static functions differently?

**Comment by stweil** [comment]
Fixed subject of PR.

**Comment by henning-gerhardt** [comment]
Every mentioned warning from above output is correct. IntelliJ IDEA reports me even more JavaDoc warnings and errors. Maybe we should use a independent JavaDoc generator as long every developer has its own settings and configuration.

**Pull request merged**
