### PR TITLE
Add 'static' attribute to inner classes without reference to parent o…

### PR DESCRIPTION
**Pull request by stweil**
…bject

This fixes warnings from FindBugs.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
Interesting. 

My findbugs (3.0.1) found 3 classes
1) Cell inside CalenderForm
2) IssueOption inside Calenderform
3) Parameters inside UserdefindedFilter
and Coverity reports only for two 2) CID 44972 and 3) CID 44990

**Comment by stweil** [comment]
As I noticed recently, newer versions of FindBugs are much better in finding problems (the number of findings increased more that twice when I switched from Debian's version 2 to latest FindBugs).
Obviously Coverity scan is conservative and does not use the latest version.

**Comment by henning-gerhardt** [comment]
Do you want add the third class to this pull request or should maybe missing class fixed in an other pull request?

**Comment by stweil** [comment]
I'd prepare another pull request to fix the remaining cases, so you can pull this one.

**Pull request merged**
