### PR TITLE
Possible fix for #431

### PR DESCRIPTION
**Pull request by matthias-ronge**
@henning-gerhardt I am not able to reproduce the problem. Can you try if this will fix it?

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I will try your fix and report back.

**Comment by henning-gerhardt** [comment]
Did not fix it :( 

New error message 

`Cannot get value for expression '#{SearchForm.operands}' `

and stack trace

```
java.lang.NullPointerException
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy51.executeQuery(Unknown Source)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1953)
	at org.hibernate.loader.Loader.doQuery(Loader.java:829)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doList(Loader.java:2438)
	at org.hibernate.loader.Loader.doList(Loader.java:2424)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2254)
	at org.hibernate.loader.Loader.list(Loader.java:2249)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:122)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1622)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
	at de.sub.goobi.forms.SearchForm.(SearchForm.java:140)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.apache.myfaces.shared_impl.util.ClassUtils.newInstance(ClassUtils.java:277)
	at org.apache.myfaces.shared_impl.util.ClassUtils.newInstance(ClassUtils.java:268)
	at org.apache.myfaces.config.ManagedBeanBuilder.buildManagedBean(ManagedBeanBuilder.java:49)
	at org.apache.myfaces.el.VariableResolverImpl.resolveVariable(VariableResolverImpl.java:314)
	at org.apache.myfaces.custom.redirectTracker.RedirectTrackerVariableResolver.resolveVariable(RedirectTrackerVariableResolver.java:41)
	at org.apache.myfaces.custom.security.SecurityContextVariableResolver.resolveVariable(SecurityContextVariableResolver.java:45)
	at org.apache.myfaces.el.ValueBindingImpl$ELVariableResolver.resolveVariable(ValueBindingImpl.java:570)
	at org.apache.commons.el.NamedValue.evaluate(NamedValue.java:124)
	at org.apache.commons.el.ComplexValue.evaluate(ComplexValue.java:140)
	at org.apache.myfaces.el.ValueBindingImpl.getValue(ValueBindingImpl.java:386)
	at javax.faces.component.UISelectItems.getValue(UISelectItems.java:58)
	at org.apache.myfaces.shared_impl.util.SelectItemsIterator.hasNext(SelectItemsIterator.java:105)
	at org.apache.myfaces.shared_impl.renderkit.RendererUtils.internalGetSelectItemList(RendererUtils.java:450)
	at org.apache.myfaces.shared_impl.renderkit.RendererUtils.getSelectItemList(RendererUtils.java:428)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlRendererUtils.internalRenderSelect(HtmlRendererUtils.java:294)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlRendererUtils.renderMenu(HtmlRendererUtils.java:267)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlMenuRendererBase.encodeEnd(HtmlMenuRendererBase.java:59)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:539)
	at org.apache.myfaces.shared_impl.renderkit.RendererUtils.renderChild(RendererUtils.java:419)
	at org.apache.myfaces.shared_impl.renderkit.RendererUtils.renderChildren(RendererUtils.java:400)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlGroupRendererBase.encodeEnd(HtmlGroupRendererBase.java:78)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:539)
	at org.apache.myfaces.shared_impl.renderkit.RendererUtils.renderChild(RendererUtils.java:419)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlGridRendererBase.renderChildren(HtmlGridRendererBase.java:229)
	at org.apache.myfaces.shared_impl.renderkit.html.HtmlGridRendererBase.encodeEnd(HtmlGridRendererBase.java:101)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:539)
	at javax.faces.webapp.UIComponentTag.encodeEnd(UIComponentTag.java:498)
	at javax.faces.webapp.UIComponentTag.doEndTag(UIComponentTag.java:366)
	at org.apache.myfaces.shared_impl.taglib.UIComponentBodyTagBase.doEndTag(UIComponentBodyTagBase.java:57)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_h_005fpanelGrid_005f6(ProzessverwaltungSuche_jsp.java:7470)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftd_005f12(ProzessverwaltungSuche_jsp.java:7326)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftr_005f8(ProzessverwaltungSuche_jsp.java:7297)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftable_005f4(ProzessverwaltungSuche_jsp.java:7195)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftd_005f10(ProzessverwaltungSuche_jsp.java:7079)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftr_005f6(ProzessverwaltungSuche_jsp.java:7037)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftable_005f3(ProzessverwaltungSuche_jsp.java:7012)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_h_005fform_005f3(ProzessverwaltungSuche_jsp.java:6814)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftd_005f9(ProzessverwaltungSuche_jsp.java:6775)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftr_005f3(ProzessverwaltungSuche_jsp.java:1878)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_htm_005ftable_005f0(ProzessverwaltungSuche_jsp.java:647)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspx_meth_f_005fview_005f0(ProzessverwaltungSuche_jsp.java:469)
	at org.apache.jsp.newpages.ProzessverwaltungSuche_jsp._jspService(ProzessverwaltungSuche_jsp.java:353)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.apache.myfaces.context.servlet.ServletExternalContextImpl.dispatch(ServletExternalContextImpl.java:419)
	at org.apache.myfaces.application.jsp.JspViewHandlerImpl.renderView(JspViewHandlerImpl.java:211)
	at org.jenia.faces.template.handler.ViewHandler.renderView(ViewHandler.java:76)
	at org.ajax4jsf.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:108)
	at org.ajax4jsf.application.AjaxViewHandler.renderView(AjaxViewHandler.java:216)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:41)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:132)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ajax4jsf.webapp.BaseXMLFilter.doXmlFilter(BaseXMLFilter.java:141)
	at org.ajax4jsf.webapp.BaseFilter.doFilter(BaseFilter.java:281)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at de.sub.goobi.helper.servletfilter.SessionCounterFilter.doFilter(SessionCounterFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at de.sub.goobi.helper.servletfilter.HibernateSessionFilter2.doFilter(HibernateSessionFilter2.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at de.sub.goobi.helper.servletfilter.SecurityCheckFilter.doFilter(SecurityCheckFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at de.sub.goobi.helper.servletfilter.RequestControlFilter.doFilter(RequestControlFilter.java:147)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:341)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

lead to [SearchForm line 140](https://github.com/goobi/goobi-production/blob/master/Goobi/src/de/sub/goobi/forms/SearchForm.java#L140).

**Comment by matthias-ronge** [comment]
And this only happens while exporting a newspaper? [This Stackoverflow post](http://stackoverflow.com/a/9680895/1503237) suggests that there might be a `NULL` field in your database where Hibernate expects a primitive. I have no idea how it could have come in there, but this would also explain why it doesn’t happen at my system. The error happens when trying to read from table `schritte` while setting up the _Search for volume_ page. There is one `short` and various `boolean`s in class `Schritt`. May you check your database? Does Hibernate write an error log?

**Comment by henning-gerhardt** [comment]
This does only happen while or after a batch export. In any other usage this error does not regular happen. So I don't think that possible `null` values in table `Schritte` are cause of this error. 

I could check rows with type 
- bit: `typMetadaten`, `typAutomatisch`, `typImportFileUpload`, `typExportRus`, `typImagesLesen`, `typImagesSchreiben`, `typExportDMS`, `typBeimAnnehmenModul`, ` 	typBeimAnnehmenAbschliessen`, `typBeimAnnehmenModulUndAbschliessen`, `typBeimAbschliessenVerifizieren`, `typScriptStep`, `batchStep`
 - smallint: `homeverzeichnisNutzen`

but this take some time.

**Comment by henning-gerhardt** [comment]
Ok, I checked bit and smallint columns: they contain only values of `0` or `1` and no `null` value.

**Comment by matthias-ronge** [comment]
The only real chance I see is adding logging output to see what is happening.

**Comment by matthias-ronge** [comment]
Browsing for [related problems on the web](https://www.google.de/search?q=NullPointerException+%22AbstractStatementProxyHandler.java:129%22) always is about an underlying database problem, a [missing table](https://joinup.ec.europa.eu/software/eusurvey/topic/eusurvey-installation), a [dead lock](https://jira.spring.io/browse/SPR-10815), … Do you see any chance to get an error log from your database?

**Comment by matthias-ronge** [comment]
Another question, does the issue only happen for the user who executed the newspaper export, or also for other users accessing the web page during that time?

**Comment by henning-gerhardt** [comment]
- any suggestions for logging and which log level?
- Mysql error logging is enabled but error log file is empty :(
- Can't say if other users are affected as I use my local development machine to locate the bug and try out your suggestions. In productive environment usage of batch exports is currently forbidden.

**Comment by matthias-ronge** [comment]
``` properties
# logs the SQL statements
log4j.logger.org.hibernate.SQL=debug 

# Logs the JDBC parameters passed to a query
log4j.logger.org.hibernate.type=trace 
```
For two users, you can test with two _different_ browsers and different user logins on your test system (one Firefox, the other one Chrome, or so).

**Comment by henning-gerhardt** [comment]
- two user test: user without batch export are not affected only user which did the export
- hibernate logging
-  produced 100GB log statements in a few seconds when enabling both options
- only enabled `log4j.logger.org.hibernate.SQL=debug` produced following log statements 
```
DEBUG 2016-02-08 12:29:35,061 (SqlStatementLogger.java:logStatement:104)
        select this_.ProjekteID as ProjekteID17_0_, this_.Titel as Titel17_0_, this_.useDmsImport as useDmsIm3_17_0_, this_.dmsImportTimeOut as dmsImpor4
_17_0_, this_.dmsImportRootPath as dmsImpor5_17_0_, this_.dmsImportImagesPath as dmsImpor6_17_0_, this_.dmsImportSuccessPath as dmsImpor7_17_0_, this_.dm
sImportErrorPath as dmsImpor8_17_0_, this_.dmsImportCreateProcessFolder as dmsImpor9_17_0_, this_.fileFormatInternal as fileFor10_17_0_, this_.fileFormat
DmsExport as fileFor11_17_0_, this_.metsRightsOwner as metsRig12_17_0_, this_.metsRightsOwnerLogo as metsRig13_17_0_, this_.metsRightsOwnerSite as metsRi
g14_17_0_, this_.metsRightsOwnerMail as metsRig15_17_0_, this_.metsDigiprovReference as metsDig16_17_0_, this_.metsDigiprovPresentation as metsDig17_17_0
_, this_.metsDigiprovReferenceAnchor as metsDig18_17_0_, this_.metsDigiprovPresentationAnchor as metsDig19_17_0_, this_.metsPointerPath as metsPoi20_17_0
_, this_.metsPointerPathAnchor as metsPoi21_17_0_, this_.metsPurl as metsPurl17_0_, this_.metsContentIDs as metsCon23_17_0_, this_.startDate as startDate
17_0_, this_.endDate as endDate17_0_, this_.numberOfPages as numberO26_17_0_, this_.numberOfVolumes as numberO27_17_0_, this_.projectIsArchived as projec
t28_17_0_ from projekte this_ order by this_.Titel asc
DEBUG 2016-02-08 12:29:35,065 (SqlStatementLogger.java:logStatement:104)
        select distinct this_.Titel as y0_ from werkstueckeeigenschaften this_ order by this_.Titel asc limit ?
DEBUG 2016-02-08 12:29:37,453 (SqlStatementLogger.java:logStatement:104)
        select distinct this_.Titel as y0_ from vorlageneigenschaften this_ order by this_.Titel asc limit ?
DEBUG 2016-02-08 12:29:41,714 (SqlStatementLogger.java:logStatement:104)
        select distinct this_.Titel as y0_ from prozesseeigenschaften this_ order by this_.Titel asc limit ?
DEBUG 2016-02-08 12:29:42,263 (SqlStatementLogger.java:logStatement:104)
        select distinct this_.Titel as y0_ from schritte this_ order by this_.Titel asc limit ?
WARN  2016-02-08 12:29:45,176 (SqlExceptionHelper.java:logExceptions:143)
        SQL Error: 0, SQLState: null
ERROR 2016-02-08 12:29:45,177 (SqlExceptionHelper.java:logExceptions:144)
        You can't operate on a closed Connection!!!

```

**Comment by matthias-ronge** [comment]
Your log exactly corresponds to the code lines [97−140](https://github.com/goobi/goobi-production/blob/master/Goobi/src/de/sub/goobi/forms/SearchForm.java#L97-L140). I am quite sure that the connection is _not_ closed in that moment and the error is misleading. There is something strange very strange going on with a `Schritt` object.

Is it possible to run the SQL query manually? It is a `select` operation which should not change something.

**Comment by henning-gerhardt** [comment]
I could run any SQL from debug statement without any issue. If they are problematic then search form would be affected in general which is not the case.

**Comment by henning-gerhardt** [comment]
I could create a workaround in my branch https://github.com/henning-gerhardt/goobi-production/tree/issue_413_hack : It does not solve root cause but search form is usable - except this select field which had a hibernate problem.

**Comment by matthias-ronge** [comment]
Does this work⁇ I do not think `Helper.getHibernateSession()` does return a useful session, it may return the closed session. If it works: better than nothing.

**Comment by henning-gerhardt** [comment]
`Helper.getHibernateSession()` must return a valid hibernate session as any later call to `session` object work as expected. I don't know why this works but it works. I will test tomorrow some use cases.

**Comment by henning-gerhardt** [comment]
I run some tests and usage scenarios

- simple batch export, switching to "search a volume"
- multiple batch exports, switching to "search a volume"
- multiple year batch export, switching to "search a volume"

work every time as expected (search form will open but one selection box is empty except default value "not selected") and every time with a logged warn message. 

I will open a pull request with my changes.

**Comment by henning-gerhardt** [comment]
Opened my changes as pull request #439.

**Comment by matthias-ronge** [comment]
I will close this pull request as it does not fix the issue.

**Pull request closed without merging**
