### PR TITLE
Add initial Travis configuration for continuous integration

### PR DESCRIPTION
**Pull request by stweil**
This is a first test based on some other pull requests, maybe not ready to get pulled.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
I think about to reject this:
- introducing travis should - if needed - a seperate pull request
- updating Java requirements are already existing as pull request and discussed (#396)
- setting supresswarning anotations already existing as pull request and discussed there (#391)

**Comment by stweil** [comment]
No need to reject this – as I wrote this is currently only a test, and it should be kept open until you have decided whether you want a Travis continuous integration test for this project or not.

Only project administrators can start the Travis integration. https://docs.travis-ci.com/user/getting-started/ describes the procedure. Steps 1 und 2 can only be done by you, step 3 and 4 are part of my pull request.

**Comment by stweil** [comment]
Here is the current Travis status for my own repository: https://travis-ci.org/stweil/goobi-production.

**Comment by henning-gerhardt** [comment]
@stweil : Your pull request contain changes which are not necessary for travis integration. This changes are inside other pull requests from you and should stay outside this pull request!

travis integration:
- building tests and war file needs Tomcat provided jar files (at least `servlet-api.jar` and maybe other). Path to this files are configured in `build.properties` (see [build template file](https://github.com/goobi/goobi-production/blob/master/build.properties.template) `tomcat.dir.lib` entry). Providing a hard coded path results in failed builds on systems where this files are located an other location.
- one or two tests failing randomly (one of ten runs or so)

**Comment by stweil** [comment]
@henning-gerhardt, of course I'll clean the pull request as soon as Travis integration works (which needs steps 1 and 2 from your side, see above).

My current Travis configuration (`.travis.yml`) adds the jar file for Tomcat using apt and uses the known path for servlet-api.jar which is only used in the Travis environment. So there should be no conflict with other build environments.

I don't understand your comment on tests failing randomly. Are you referring to the results on https://travis-ci.org/stweil/goobi-production/builds? There is no random result – all those results mark different states of my Travis integration efforts. The green one is the current valid one.

Currently my Travis integration tests building of the war file, so it will detect compilation failures introduced by new pull requests. I am still struggling with running the tests in the Travis environment, but that can be added in a later step.

**Comment by henning-gerhardt** [comment]
Sorry, I did not understand to add first different changes to remove them later. Unnecessary work - IMHO.

Regarding tests: I meant running Goobi test with ant resulting in randomly failed tests and not the failed travis builds of your fork.

**Comment by stweil** [comment]
To avoid further confusion, I removed the parts which are not strictly needed for Travis. Of course #396 is important for the compilation test because some compiler warnings / errors depend on the Java version, but it can also be pulled later.

Which of the current tests fail randomly? I'm sure that can be fixed. As long as we don't run those tests in Travis, it is an unrelated issue.

**Comment by henning-gerhardt** [comment]
I think tests inside `org.goobi.production.flow.statistics.StatisticsManagerTest` failing randomly when running `ant test` on command line.

**Comment by stweil** [comment]
Could you please open an issue for those failing tests and show the test output there?

I just tried `ant test` 10 times and got no fail.

**Comment by stweil** [comment]
@henning-gerhardt, you are running those tests on Windows, are you? Then I might know the reason for the random failures. It should be easy to fix.

**Comment by henning-gerhardt** [comment]
I run any tests and distribution building on Debian Linux - so no Windows error.

**Comment by stweil** [comment]
Pull request #426 fixes the problems with `ant test` and `ant docs`, so Travis can now run `ant all`. See https://travis-ci.org/stweil/goobi-production/builds/106268054 for an example.

**Comment by stweil** [comment]
Updated pull request, now runs `ant all`.

**Comment by stweil** [comment]
I forgot to mention that this pull requests is ready to get pulled. It can be used for clones of goobi-production and for goobi/goobi-production. Travis tests only run if they are enabled by the owner of a GitHub repository, so I could enable them for stweil/goobi-production, but not for goobi/goobi-production.

**Comment by henning-gerhardt** [comment]
I will merge this pull request but add travis integration for this repo later.

**Pull request merged**
