### PR TITLE
Replace inefficient Boolean constructor

### PR DESCRIPTION
**Pull request by stweil**
This fixes a warning from FindBugs.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by matthias-ronge** [comment]
Why not `this.ughbinding = toCopy.ughbinding;`? Am I missing something here?

**Comment by stweil** [comment]
@matthias-ronge, we need a conversion from boolean to Boolean here. See also https://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html.

**Comment by matthias-ronge** [comment]
`toCopy` is a `Field`, so `toCopy.ughbinding` cannot be something else than `Boolean`. Moreover Java would do autoboxing if it was `boolean`. Or am I now barking up the wrong tree?

**Comment by stweil** [comment]
When looking closer on the code, I think that you are right. It looks like a simple assignment would be sufficient:

    this.ughbinding = toCopy.ughbinding;

**Comment by henning-gerhardt** [comment]
After reading [javadoc comment](https://github.com/goobi/goobi-production/blob/master/Goobi/src/org/goobi/webapi/beans/Field.java#L66-L72) and try to interpret [lines of code](https://github.com/goobi/goobi-production/blob/master/Goobi/src/org/goobi/webapi/beans/Field.java#L77-L82), maybe following was goal of implementation: hard copying values of given object as cloning object duplicate any other references too. Main goal could be preventing any miss-usage in web context.

If maybe exploding of this objects is not possible or I miss-interpret something wrong, lines [80](https://github.com/goobi/goobi-production/blob/master/Goobi/src/org/goobi/webapi/beans/Field.java#L80) and [82](https://github.com/goobi/goobi-production/blob/master/Goobi/src/org/goobi/webapi/beans/Field.java#L82) should be changed.

**Comment by stweil** [comment]
@matthias-ronge, maybe you can say more on the original code, the comment and whether my simplification is valid or not.

**Comment by matthias-ronge** [comment]
Line 82 is not needed, because the internal meaning of `Boolean.TRUE` or `Boolean.FALSE` will not change. If for a field `ughbinding` state should be changed the field will no longer point to the `Boolean.TRUE` object in memory, but to the `Boolean.FALSE` object.
_If Bob and Alice both point with their finger onto a red apple, and Bob changes his mind and then points his finger on a green apple, Alice can still point to the red apple._ (The apples here are **immutable**. They do _not change_ their colour.)

It is different for the list. If for one field the options are changed, the _internal_ state of the list changes, so it would influence on another object which points to the same list in memory. Therefore a copy of the list is created to prevent this.
_If Bob and Alice both point with their finger onto the same table, and Bob puts three more apples on the table, Alice does suddanly find three more apples on the table she points her finger to._ (The table here is **mutable**. It _changes_ its state.)
_We need to give Alice her own table to prevent her from surprises._ → That is why the list copy happens.

**Comment by matthias-ronge** [comment]
The copy constructor is never used from within the code. It can be deleted.

**Comment by henning-gerhardt** [comment]
It is not used, removing should not harm anybody.

**Comment by stweil** [comment]
It wouldn't harm now, but might harm later if anybody adds code which implies using the copy constructor. What about adding a private copy constructor (with no code)? Then the Java compiler will prevent accidental usage.

**Comment by matthias-ronge** [comment]
Removing it will be the same, you could no longer compile a class calling a non-existent constructor. I think it is a good point to remove unused code from the project.

**Comment by henning-gerhardt** [comment]
+1 for removing unused code.

**Comment by henning-gerhardt** [comment]
If this constructor is removed, then other class constructor is needed too? Comment in lines [56 to 60 ](https://github.com/stweil/goobi-production/blob/findbugs/Goobi/src/org/goobi/webapi/beans/Field.java#L56-L60) could be interpret as this constructor is only needed for second constructor.

**Comment by stweil** [comment]
Good catch. The commit now removes all constructors.

**Pull request merged**
