### PR TITLE
Fix possible null pointer dereference

### PR DESCRIPTION
**Pull request by stweil**
FindBugs reports this warning:
	Possible null pointer dereference in method on exception path

Fix it by moving the relevant code into the try block.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
It is not a fix to move code inside a try catch block to catch a possible null pointer exception.

**Comment by stweil** [comment]
It is. The null pointer occurred because a local variable was set to null and accessed after the try / catch block, even if its value was not changed because an exception had occurred. Now it is only used in the try block where its value is set before use.

**Comment by henning-gerhardt** [comment]
Whole method need some love:
- Every exception is catched but only `ParserConfigurationException`, `IOException`, `SAXException` and `IllegalArgumentException` are thrown.
- catched exception prints only a stack trace instead of logged error
- after catched exception code goes on and a possible null pointer exception occurs

IMHO if an exception are catched method should return and not change any value

**Comment by henning-gerhardt** [comment]
Simple and correct fix is to add an`return` statement inside catch block.

**Comment by stweil** [comment]
@henning-gerhardt, that's also a possible solution, but your fix requires an additional code line while my patch was able to remove two code lines (the null assignments).

**Comment by henning-gerhardt** [comment]
I looked into java doc description of `parse()` method of `DocBuilder` class
```java
/**
     * Parse the content of the given URI as an XML document
     * and return a new DOM {@link Document} object.
     * An <code>IllegalArgumentException</code> is thrown if the
     * URI is <code>null</code> null.
     *
     * @param uri The location of the content to be parsed.
     *
     * @return A new DOM Document object.
     *
     * @throws IOException If any IO errors occur.
     * @throws SAXException If any parse errors occur.
     * @throws IllegalArgumentException When <code>uri</code> is <code>null</code>
     *
     * @see org.xml.sax.DocumentHandler
     */

    public Document parse(String uri)
        throws SAXException, IOException {
        if (uri == null) {
            throw new IllegalArgumentException("URI cannot be null");
        }

        InputSource in = new InputSource(uri);
        return parse(in);
    }
```

Used method returning a new Object or throw an exception in error case. If you catch the exceptions and let your method return in this case no future check is necessary. Or did I oversee something?

**Comment by henning-gerhardt** [comment]
IMHO: try catch statements should be small as possible and only catch thrown exceptions and not programmer errors.

**Comment by henning-gerhardt** [comment]
After analysing usage of this method with IDEA this method could be removed. `picaToKey` and `picaToDescription` are never used. I don't know if this an old feature or a never correct implemented feature.

**Comment by stweil** [comment]
@henning-gerhardt, that's correct, the community edition does not use it. The Intranda edition does - that's why I hesitate to remove the code.

**Comment by henning-gerhardt** [comment]
I see there no problem: If some changes as prober pull-request from Intranda edition come back to community edition this removed lines come back too. If changes go from community edition to Intranda edition this lines will be removed too.

Should we really look into every single branch / fork every time when we change something and cancel this change because somewhere something got broken which is maintained by somebody else? I don't think so.

**Comment by stweil** [comment]
Closed because this patch is superseeded by #406.

**Pull request closed without merging**
